### ISSUE TITLE
Trying to get the code to compile

### ISSUE THREAD

**Issue by suryatech** [nasa/kepler-pipeline#1]
I believe the project uses ANT for dependency management. I couldn't find any instructions on building the java source code in the project.

I tried running `ant -s .` under `source-code/java` and it returns the following error:

```
➜  java git:(master) ✗ ant -s .
Searching for . ...
Buildfile: /Users/surya/dev/kepler-pipeline/source-code/java/build.xml
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.

BUILD FAILED
/Users/surya/dev/kepler-pipeline/source-code/java/build.xml:46: The following error occurred while executing this line:
/Users/surya/dev/kepler-pipeline/source-code/java/include/ant/standard.xml:70: The following error occurred while executing this line:
/Users/surya/dev/kepler-pipeline/source-code/java/include/ant/findbugs.xml:45: taskdef class edu.umd.cs.findbugs.anttask.FindBugsTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```

Are there any basic setup scripts/jars that need to be downloaded to get the project to compile?

@wohler

**Comment by wohler** [comment]
Sorry that I didn't see your note until now! The answer to your question is in the README:

Please note that it is not expected that the reader will be able to build or run this this software due to third-party licensing restrictions and dependencies and other complications.

**Comment by toddklaus** [comment]
I had a hard time getting it to compile too, Bill.
